name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"
[commands]
predev = "npm exec prisma generate"
dev = "sh scripts/migrate-dev.sh && npx react-router dev --port 3458 --host 0.0.0.0"
